name: Auto Closer PR

on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    name: ğŸ¤– PR Auto-Closure
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            Hi there ğŸ‘‹,

            First off, thanks for your effort! ğŸ‰ Unfortunately, this repository is read-only because it's split from our primary monorepo repository.

            ğŸ™ We kindly ask if you could direct your valuable contribution to our main repository at https://github.com/php-flasher/php-flasher.

            Once you've moved your contribution there, we'll review it and provide feedback. ğŸ•µï¸â€â™‚ï¸

            Thanks again for your understanding and cooperation. We really appreciate it! ğŸ™Œ
