name: Running tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '* * * * *'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [ 8.0, 7.4, 7.3, 7.2, 7.1, 7.0, 5.6, 5.5, 5.4 ]

        name: php ${{ matrix.php }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Require phpunit 4.8 for php <= 5.6
                if: matrix.php <= 5.6
                run: composer require "phpunit/phpunit:4.8.36" --no-interaction --no-update

            -   name: Require phpunit 6 for php >= 7.0
                if: matrix.php >= 7.0
                run: composer require "phpunit/phpunit:6.*" --no-interaction --no-update

            -   name: Require phpunit 9 for php >= 7.3
                if: matrix.php >= 7.3
                run: composer require "phpunit/phpunit:9.*" --no-interaction --no-update

            -   name: Install dependencies
                run: composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit
